### ISSUE TITLE
Gitignore File

### ISSUE THREAD

**Issue by erayaydin** [codevinsky/generator-phaser-official#10]
Hello,

Firstly, thank you for this tool. GPO is **AWESOME!**

I think .gitignore file *must* include
```
# GRUNT #
dist/
.tmp/

# BOWER #
bower_components

# NPM #
node_modules
pids
*.pid
*.seed
.grunt

# LOGS #
logs
*.log

# Linux #
*~
.directory

# Windows #
## I HATE Windows...
Thumbs.db
ehthumbs.db
Desktop.ini
$RECYCLE.BIN/
*.lnk
```

Thank you.

**Comment by erayaydin** [comment]
any news ?

**Comment by budda** [comment]
@erayaydin Remove the silly comment "## I HATE Windows..." and why not generate a pull-request by editing the original file right here on github.com to make it easier for the change to be merged in if the project owner likes it ?
