### ISSUE TITLE
Gets stuck at waiting on localhost...

### ISSUE THREAD

**Issue by lobo-tuerto** [codevinsky/generator-phaser-official#13]
After running the generator and then running grunt, the terminal reads:

```
Running "buildBootstrapper" task
{ projectName: 'phaser game',
  gameWidth: '800',
  gameHeight: '600',
  gameStates: 
   [ { shortName: 'boot', stateName: 'BootState' },
     { shortName: 'gameover', stateName: 'GameoverState' },
     { shortName: 'menu', stateName: 'MenuState' },
     { shortName: 'play', stateName: 'PlayState' },
     { shortName: 'preload', stateName: 'PreloadState' } ] }

Running "browserify:build" (browserify) task
>> Bundled dist/js/game.js

Running "copy:dist" (copy) task
Created 2 directories, copied 6 files

Running "connect:livereload" (connect) task
Starting connect web server on localhost:9000.

Running "open:server" (open) task

Running "watch" task
Waiting...
```
It opens the browser, but it only shows a blank screen and the load indicator never stops, the status bar reads: Waiting localhost...

No errors on the web console.

**Comment by Clonk-HTML5** [comment]
I got the same problem !!

**Comment by cjke** [comment]
I got the same problem. I believe I know the fixing - I will set up a pull request now

**Comment by Clonk-HTML5** [comment]
Thank you for your pull request, it is working.

**Comment by cjke** [comment]
Cool good to hear

**Comment by budda** [comment]
Would be nice to get this merged back in as the current version doesn't work at all as-is.

**Comment by cjke** [comment]
I have submitted a merge request. I don't believe it will get merged back in to master though as the project seems dead

**Comment by budda** [comment]
The author was on the Phaser Slack channel last night. So they are still
active with Phaser at least. Maybe some hope there.....!

**Comment by charliemc** [comment]
I'm still experiencing this issue, any news?

**Comment by cjke** [comment]
You can just pull my fork (https://github.com/cjke/generator-phaser-official) - it is identical to current master except it has this bug fixed.

**Comment by charliemc** [comment]
Thank you @cjke, that worked!

**Comment by cjke** [comment]
No worries
